apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsspring
  labels:
    app: newsspring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsspring
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: newsspring
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
        - name: newsspring
          image: registry.gitlab.com/dpapajohn/newsspring:ci-test
          
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2